apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-config
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  LOCATIONAPI_EVENTS_PUBLISHER_PREFIX: "{{ .Values.api.events.topicPrefix }}"
  LOCATIONAPI_EVENTS_PUBLISHER_URL: "{{ .Values.api.events.connectionURL }}"
  LOCATIONAPI_OIDC: "{{ .Values.api.oidc.enabled }}"
  LOCATIONAPI_OIDC_AUDIENCE: "{{ .Values.api.oidc.audience }}"
  LOCATIONAPI_OIDC_ISSUER: "{{ .Values.api.oidc.issuer }}"
  LOCATIONAPI_OIDC_JWKS_REMOTE_TIMEOUT: "{{ .Values.api.oidc.jwksRemoteTimeout }}"
  LOCATIONAPI_SERVER_LISTEN: ":{{ .Values.api.listenPort }}"
  LOCATIONAPI_SERVER_SHUTDOWN_GRACE_PERIOD: "{{ .Values.api.shutdownGracePeriod }}"
{{- with .Values.api.trustedProxies }}
  LOCATIONAPI_SERVER_TRUSTED_PROXIES: "{{ join " " . }}"
{{- end }}
